services:
  python-kata:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: python-kata-machine
    volumes:
      - .:/kata-machine
      - kata-machine-cache:/home/kata-user/.cache
    working_dir: /kata-machine
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/kata-machine
    
volumes:
  kata-machine-cache:
