"""
Day 1 - Python Kata Practice
Generated by Python Kata-Machine

Algorithms to implement:
- LinearSearch
- BinarySearchList
- TwoCrystalBalls
- BubbleSort
- InsertionSort
- MergeSort
- QuickSort
- Queue
- Stack
- ArrayList
- SinglyLinkedList
- DoublyLinkedList
- BTPreOrder
- BTInOrder
- BTPostOrder
- BTBFS
- CompareBinaryTrees
- DFSOnBST
- BFSGraphMatrix
- DFSGraphList
- Dijkstra
- PrimsList
- Trie
- LRU
- Map
"""

# Import all algorithms for easy access
from .linear_search import linear_search
from .binary_search_list import binary_search_list
from .two_crystal_balls import two_crystal_balls
from .bubble_sort import bubble_sort
from .insertion_sort import insertion_sort
from .merge_sort import merge_sort
from .quick_sort import quick_sort
from .queue import queue
from .stack import stack
from .array_list import array_list
from .singly_linked_list import singly_linked_list
from .doubly_linked_list import doubly_linked_list
from .b_t_pre_order import b_t_pre_order
from .b_t_in_order import b_t_in_order
from .b_t_post_order import b_t_post_order
from .b_t_b_f_s import b_t_b_f_s
from .compare_binary_trees import compare_binary_trees
from .d_f_s_on_b_s_t import d_f_s_on_b_s_t
from .b_f_s_graph_matrix import b_f_s_graph_matrix
from .d_f_s_graph_list import d_f_s_graph_list
from .dijkstra import dijkstra
from .prims_list import prims_list
from .trie import trie
from .l_r_u import l_r_u
from .map import map

# Export all algorithms
__all__ = [
    "linear_search",
    "binary_search_list",
    "two_crystal_balls",
    "bubble_sort",
    "insertion_sort",
    "merge_sort",
    "quick_sort",
    "queue",
    "stack",
    "array_list",
    "singly_linked_list",
    "doubly_linked_list",
    "b_t_pre_order",
    "b_t_in_order",
    "b_t_post_order",
    "b_t_b_f_s",
    "compare_binary_trees",
    "d_f_s_on_b_s_t",
    "b_f_s_graph_matrix",
    "d_f_s_graph_list",
    "dijkstra",
    "prims_list",
    "trie",
    "l_r_u",
    "map",
]
